type DeleteResponse {
  message: String!
  isSuccess: Boolean!
}

type FocusArea {
  id: ID!
  name: String!
  label: String!
}

input FocusAreaInput {
  name: String!
  label: String!
}

type Mutation {
  createPost(
    title: String!
    content: String!
    focusAreas: [FocusAreaInput!]!
  ): Post!
  createComment(content: String!, postId: Int!): Comment
  deletePost(postId: Int!): DeleteResponse!
}
