type Post {
  id: ID!
  title: String!
  content: String!
  slug: String!
  focusAreas: [FocusArea!]!
  createdAt: String!
  user: User!
  comments: [Comment!]!
}

type PaginatedPost {
  posts: [Post!]!
  nextCursor: String
  hasNextPage: Boolean
}

type PostResponse {
  post: Post!
  isOwnComment: Boolean!
}
